name: Mobile Update
on:
  workflow_run:
    workflows: ["Project Deployment"]
    types:
      - completed
  push:
    branches:
      - teste-actions
jobs:
  Mobile-Update:
    runs-on: ubuntu-latest
    environment: pre-main
    needs: Deploy-Preview-To-Vercel
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: npm
          cache-dependency-path: Mobile/package-lock.json
        
      - name: 🏗 Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN_DEV }}

      - name: 📦 Install dependencies
        working-directory: ./Mobile
        run: npm install

      - name: 🚀 Create preview
        uses: expo/expo-github-action/preview@v8
        env:
          SERVER_LINK: ${{needs.Deploy-Preview-To-Vercel.outputs.output1}}
          GOOGLE_MAP_API_KEY: ${{ secrets.GOOGLE_MAP_API_KEY }}
        id: preview
        with:
          command: eas update --auto
          comment: false
          working-directory: ./Mobile
        # run: eas build --non-interactive --platform android
        # run: eas update --auto
      - name: teste
        run: |
          echo "Id ${{ steps.preview.outputs.groupId }}"
          echo "QRCode: ${{ steps.preview.outputs.qr }}"
          echo "androidId ${{ steps.preview.outputs.androidId }}"
          echo "androidQR ${{ steps.preview.outputs.androidQR }}"
          echo "iosId ${{ steps.preview.outputs.iosId }}"
          echo "iosQR ${{ steps.preview.outputs.iosQR }}"

# https://vercel.com/docs/cli/deploy#standard-output-usage
# https://docs.expo.dev/develop/development-builds/share-with-your-team/
# https://docs.expo.dev/eas-update/github-actions/#publish-previews-on-pull-requests
# https://github.com/expo/expo-github-action/tree/main/preview#readme


# https://docs.expo.dev/build-reference/variants/

# https://github.com/endroid/qr-code/blob/main/README.md