name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  
  SGBD: ${{ secrets.SGBD }}
  HOST: ${{ secrets.VERCEL_PROJECT_ID }}
  PORT: ${{ secrets.PORT }}
  DATABASE: ${{ secrets.DATABASE }}
  USER: ${{ secrets.USER }}
  PASSWD: ${{ secrets.PASSWD }}
  DISPLAY_ERROR: ${{ secrets.DISPLAY_ERROR }}
on:
  push:
    branches:
      - main
    paths:
      - 'API/PHP/slim/**'
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    environment: pre-main
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
